config/routes.rb
Railsgirls::Application.routes.draw do

  get "sessions/new"

  get "sessions/create"

  get "sessions/failure"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
 
  root :to => 'events#index'


get   '/login', :to => 'sessions#new', :as => :login
match '/auth/:provider/callback/', :to => 'sessions#create'
match '/auth/failure', :to => 'sessions#failure'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
	validates :provider, :uid, :presence => true
  attr_accessible :provider, :uid, :user_id
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :amount, :email, :name, :twitter, :created_on, :event_id
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :day, :goal, :name
  has_many :expenses
  has_many :donations
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :created_on, :description, :price, :quantity, :event_id
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :authorizations
	validates :name, :email, :presence =>true
    attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
    @total = 0

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @expenses = Expense.all
    @donations = Donation.all
    @expenses_total = Expense.sum('price * quantity')
    @donations_total = Donation.sum('amount')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
    @total = 0

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.json
  def new
    @expense = Expense.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(params[:expense])

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render json: @expense, status: :created, location: @expense }
      else
        format.html { render action: "new" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.json
  def update
    @expense = Expense.find(params[:id])

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
    auth = request.env["omniauth.auth"]
    user = Authorization.find_by_provider_and_uid(auth["provider"], auth["uid"]) || Authorization.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
end

  def failure
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
   <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Twitter</th>
    <th>Email</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.name %></td>
    <td><%= donation.twitter %></td>
    <td><%= donation.email %></td>
    <td><%= donation.amount %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% @total = @total + donation.amount %>
<% end %>
</table>

<h2>Total: <%= @total %></h2>
<br />

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donation.name %>
</p>

<p>
  <b>Twitter:</b>
  <%= @donation.twitter %>
</p>

<p>
  <b>Email:</b>
  <%= @donation.email %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.date_select :day %>
  </div>
  <div class="field">
    <%= f.label :goal %><br />
    <%= f.text_field :goal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
		<% if current_user %>
	  Welcome <%= current_user.name %>!

	<% else %>
	 No current
	 <%end%>



Hola! Si has llegado a esta página es porque sabes que estamos organizando el primer <a href="http://railsgirls.com/lima">Rails Girls en Lima</a>. Este evento será gratuito y está dirigido a despertar el interés de chicas en la tecnología Ruby on Rails. Ya tenemos local, fecha y hasta coaches. Sin embargo, nos hace falta presupuesto para comprar unas <a href="https://docs.google.com/spreadsheet/ccc?key=0AvNGZfgqU1PZdFhqa05CYW5KSEdYWEJFSTdia2w5ekE&usp=sharing">cosas básicas</a>, y por eso necesitamos tu apoyo! Toda ayuda es bienvenida, sólo <a href="mailto:railsgirlslima@gmail.com">envíanos un correo</a> para enviarte más información :)
<% if !@events.first.nil? %>
<h2>Nuestra meta: S/. <%= number_with_precision(@events.first.goal, :precision => 2) %></h2>
<%
progress = @donations_total / @events.first.goal

if (progress > 1) then 
	progress = 1
end
 %>

Colaboraciones al <%= number_with_precision(progress * 100, :precision => 0) %>%
<div id="progressbarcontainer">
<div id="progressbar"></div>
</div>

<script>
$( "#progressbar" ).css("width", "<%= progress * 100 %>%");
</script>

<div class="centering">
<h2>Quedan</h2>
<div id="countdown"></div>
<script>
date = new Date(<%= @events.first.day.year %>, <%= @events.first.day.month %>-1, <%= @events.first.day.day %>);
$('#countdown').countdown({until: date});
</script>
<p>Día del evento: <%= @events.first.day %></p>
</div>
<div id="agradecimientos">
<h2>Agradecimientos</h2>
<table>
<% @donations.each do |donation| %>
	<tr><td>
		<%= donation.twitter.empty?? donation.name : link_to(donation.name, "http://twitter.com/" + donation.twitter)  %></td><td>S/. <%= number_with_precision(donation.amount, :precision => 2) %></td></tr>
<% end %>
</table>
</div>
<br />
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Day:</b>
  <%= @event.day %>
</p>

<p>
  <b>Goal:</b>
  <%= @event.goal %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :created_on %><br />
    <%= f.date_select :created_on %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Quantity</th>
    <th>Price</th>
		<th>Sub-total</th>
    <th>Created on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= expense.description %></td>
    <td><%= expense.quantity %></td>
    <td><%= expense.price %></td>
		<td><%= expense.price*expense.quantity %></td>
    <td><%= expense.created_on %></td>
    <td><%= link_to 'Show', expense %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% @total = @total + expense.price*expense.quantity %>
<% end %>
</table>

<h2>Total: <%=@total%></h2>

<br />

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @expense.description %>
</p>

<p>
  <b>Quantity:</b>
  <%= @expense.quantity %>
</p>

<p>
  <b>Price:</b>
  <%= @expense.price %>
</p>

<p>
  <b>Created on:</b>
  <%= @expense.created_on %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<div>
	<% if current_user %>
	  Welcome <%= current_user.name %>!

	<% else %>
	  <%= link_to "Sign in with Facebook", "/auth/facebook" %>
	<% end %>
</div>

  <title>Railsgirls Lima</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">

	<h1><a href="http://railsgirls.com/lima">Rails Girls<br/>Lima</a></h1>

	
</div>
<div id="page">
<%= yield %>
	<div id="sharethelove">
<a href="http://railsgirls.com/lima">Regístrate al evento</a> | <a href="https://docs.google.com/spreadsheet/ccc?key=0AvNGZfgqU1PZdFhqa05CYW5KSEdYWEJFSTdia2w5ekE&usp=sharing">Lista de Compras</a> | <a href="mailto:railsgirlslima@gmail.com">Contáctanos</a> 
<p> 
<a href="https://twitter.com/share" class="twitter-share-button" data-text="Apoya a Rails Girls Lima, estamos buscando colaboradores :3" data-hashtags="railsgirlslima">Tweet</a>
								<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</p>
	</div>
</div>

</body>
</html>